workflows:
  android-debug-workflow:
    name: Android Debug Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Generate Gradle wrapper
        script: |
          gradle wrapper --gradle-version=9.3.1
      - name: Make Gradle executable
        script: |
          chmod +x gradlew
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
